//

#define LIMITS_STR_SIZE 64

enum _: DATA_SAVE_LIMITS {
	LIMIT_RANK_MONEY,
	LIMIT_RANK_HEALTH,
	LIMIT_RANK_GRENADES,
	LIMIT_RANK_FREEDAY,
	LIMIT_RANK_GLOCK,
	LIMIT_RANK_EL_COSTUME,
	LIMIT_RANK_KOKAIN,
	LIMIT_RANK_GOD,

	LIMIT_VIP_MONEY,
	LIMIT_VIP_INVISIBLE,
	LIMIT_VIP_HP_AP,
	LIMIT_VIP_GHOST,
	LIMIT_VIP_GOD,
	LIMIT_VIP_FOOTSTEPS
};
